services:
  - type: web
    name: mufate-backend
    env: docker
    repo: https://github.com/Clive-MM/MUFATE-G-SACCO
    branch: main
    rootDir: server
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
